"""inserted event_date column in events

Revision ID: 4a99f4fbd9ee
Revises: ec14f67eac4b
Create Date: 2023-10-16 12:05:36.300396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a99f4fbd9ee'
down_revision = 'ec14f67eac4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###
